version: '3'
services:
  go_server:
    build: .
    ports:
    - "8082:8082"
    network_mode: host
  redis:
    image: redis
  emqx:
    image: emqx/emqx
    ports:
    - 18083:18083
    - 1883:1883
    - 8883:8883
  nginx:
    image: nginx
    restart: always
    ports:
    - 8083:80
